name: CI with Job Dependencies and Conditionals

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: echo "Building the project..."

      - name: Run Tests
        run: echo "Running tests..."
        id: test

      - name: Upload Test Results
        if: success() # This step runs only if all previous steps succeed
        run: echo "Uploading test results..."
        
      - name: Notify Failure
        if: failure() # This step runs only if any of the previous steps fail
        run: echo "Notify: Something went wrong!"

  deploy:
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "Deploying the project..."
