name: Example Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_variable: ${{ steps.step1.outputs.my_variable }}
    steps:
      - name: Set output variable
        id: step1
        run: echo "::set-output name=my_variable::$(date +%Y-%m-%d)"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use output variable from job1
        run: echo "The variable from job1 is ${{ needs.job1.outputs.my_variable }}"
