name: Pass Name Variable

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.step1.outputs.name }}
    steps:
      - name: Set name variable
        id: step1
        run: echo "::set-output name=name::Chandan Mohan"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Display name from job1
        run: echo "The name from job1 is ${{ needs.job1.outputs.name }}"
